clear; clc; close all; dbstop if error;

%% RADIOS

% Rx = comm.SDRuReceiver("Platform", RxCfg.Platform, ...
%     "SerialNum", RxCfg.SerialNum, ...
%     "CenterFrequency", centerFrequency, ...
%     "ChannelMapping", RxChannelMapping, ...
%     "ClockSource", ClockSource, ...
%     "EnableBurstMode", enableBurstMode, ...
%     "Gain", RxGain, ...
%     "LocalOscillatorOffset", LOOffset, ...
%     "MasterClockRate",  MasterClockRate, ...
%     "NumFramesInBurst", nFramesInBurstMode, ...
%     "PPSSource", PPSSource, ...
%     "TransportDataType", dataType, ...
%     "DecimationFactor",InterpolationDecimationFactor);

%% SEND DATA

pause(0.5);
[Tx, time, underrun] = sendSinewave();
% [Tx, time, underrun] = sendData();

%% CLEAN EXIT

release(Tx);
