function [] = set_path()
%SET_PATH Summary of this function goes here
%   Detailed explanation goes here

addpath("data", ...
 "../libs/functions", ...
 "../libs/generators", ...
  "../libs/libcom", ...
  "../libs/libhilbert", ...
  "../libs/libplot", ...
  "../libs/libpseudosemantic", ...
  "../libs/libsig", ...
  "../libs/libsim", ...
  "../libs/libwalsh", ...
  "../libs/libwalsh/mod");
end

