restoredefaultpath; clear RESTOREDEFAULTPATH_EXECUTED;
addpath("data", ...
    "../libs/functions", ...
    "../libs/generators", ...
    '../libs/libcom', ...
    "../libs/libhilbert", ...
    "../libs/libplot", ...
    "../libs/libsig", ...
    "../libs/libsim", ...
    "../libs/libwalsh", ...
    "../libs/libwalsh/mod", ...
    "../libs/libpseudosemantic", ...
    "visuals");